name: ReportSystem
version: 1.0.0
api: 5.0.0
src-namespace-prefix: lokiPM\ReportSystem
main: lokiPM\ReportSystem\Main

commands: 
 report:
  description: Report a Player.
  default: true
  permission: report.use
 reportreload:
  description: Reload the Plugin.
  default: op
  permission: report.reload

permissions:
 report.use:
  default: true
 report.reload:
  default: op
